### ISSUE TITLE
Structural suggestion SDG7

### ISSUE THREAD

**Issue by EliSeland** [SDGforskning/sdg-strings#18]
SDG: 7

Target & Phrase: 3.1., Phrase 3, Topic approach

Suggestion: Consider removing "heating" from second part of phrase - look at relation to "coal" (industrial)

Reason: To be aligned with the explanation given in the documentation (to do with conversion action - topic)

**Comment by hmbjerkan** [comment]
From duplicate issue (closed):
SDG: 7
Target: 7.1
Action or Topic?: Topic

Feedback: A few irrelevant results appear, due to Phrase 3 which allows hits on 'coal' AND 'heating'. These results relates to coal mining og coal processing.

Example result:
http://dx.doi.org/10.1080/15567036.2023.2179693
http://dx.doi.org/10.1080/15567036.2023.2186541
